require('../state_test');
require('../api_test');
require('../models/config_test');
require('../models/map_test');
require('../models/marker_test');
require('../models/server_test');
require('../models/user_test');
require('../views/google-map_test');
require('../views/main_test');